budget_app/urls.py
from django.urls import path
from . import views


app_name = 'budget_app'
urlpatterns = [
    path('', views.budget_dashboard, name='budget_dashboard'),
    path('expense/new', views.new_expense, name='new_expense'),
    path('expense/<int:expense_id>/' ,views.expense_detail, name='expense_detail'),
    path('transaction', views.transaction_detail, name='transaction_detail'),
    path('expense/delete/<int:expense_id>/',views.del_expense, name='del_expense'),
    path('transaction/new', views.new_transaction, name='new_transaction'),
    path('expense/category/new', views.new_category_expense, name = 'new_category_expense'),
    path('transaction/category/new', views.new_category_transaction, name='new_category_transaction'),
    path('month_new', views.add_next_month, name = 'add_next_month')
    
]

budget_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('budget_app.urls')),
    path('admin/', admin.site.urls),
]

budget_app/models.py
from django.db import models
from datetime import date


class Category(models.Model):
    name = models.CharField(max_length=64)
    
    def __str__(self):
      return self.name

class Expense(models.Model):
    month = models.DateField(default=date.today)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    allocated = models.DecimalField(max_digits=8, decimal_places=2)
    disbursed = models.DecimalField(max_digits=8, decimal_places=2)
    remaining = models.DecimalField(max_digits=8, decimal_places=2)

    class Meta:
        get_latest_by = 'month'

    def __str__(self):
        return f'{self.category} {self.month}'

class Transaction(models.Model):
    date = models.DateField(default=date.today)
    recipient = models.CharField(max_length=64)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    inflow = models.DecimalField(max_digits=8, decimal_places=2)
    outflow = models.DecimalField(max_digits=8, decimal_places=2)
    note = models.TextField()

    def __str__(self):
        return f'{self.recipient} {self.category} {self.note}'

budget_app/forms.py
from django import forms
from .models import Expense, Transaction, Category

class NewExpenseForm(forms.ModelForm):

    class Meta:
        model = Expense
        fields = ('category',)

class UpdateAllocationForm(forms.Form):
    allocate = forms.DecimalField(max_digits=8, decimal_places=2)

class NewTransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = ('date', 'recipient', 'category', 'inflow', 'outflow', 'note')

class NewCategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('name',)

budget_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum
from .models import Expense, Transaction
from .forms import NewTransactionForm, NewExpenseForm, UpdateAllocationForm, NewCategoryForm
from datetime import date, timedelta
from decimal import Decimal as dc
from .utils import update_expense, latest_months_expenses, new_month

def budget_dashboard(request):
    expenses = latest_months_expenses()
    total_transactions = Transaction.objects.all().aggregate(Sum('inflow'))['inflow__sum'] or dc(0.00)
    total_allocations = expenses.aggregate(Sum('allocated'))['allocated__sum'] or dc(0.00)
    unbudgeted = total_transactions - total_allocations
    context = {
            'expenses':expenses,
            'unbudgeted':unbudgeted,
    }

    return render(request, 'budget_app/dashboard.html', context)


def new_transaction(request):
    if request.method == 'POST':
        transaction_form = NewTransactionForm(request.POST)


        if transaction_form.is_valid():
            transaction_added = transaction_form.save(commit=False)
            update_expense(transaction_added)
            transaction_added.save()
            return redirect('/')

    else:
        transaction_form = NewTransactionForm()
        category_form = NewCategoryForm()
        context = {
            'transaction_form': transaction_form,
            'category_form': category_form
            }
        return render(request, 'budget_app/transaction_new.html', context)


def new_expense(request):
    if request.method == 'POST':
        expense_form = NewExpenseForm(request.POST)

        if expense_form.is_valid():
            expense_added = expense_form.save(commit=False)
            expense_added.allocated = 0.00
            expense_added.disbursed = 0.00
            expense_added.remaining = 0.00
            expense_added.month = expense_added.month.replace(day=1)
            expense_added.save()
            return redirect('/')

    else:
        category_form = NewCategoryForm()
        expense_form = NewExpenseForm()
        return render(request, 'budget_app/expense_new.html', {'expense_form': expense_form, 'category_form':category_form})


def expense_detail(request, expense_id):
    specific_expense = get_object_or_404(Expense, pk=expense_id)

    if request.method == 'POST':
        allocated_form = UpdateAllocationForm(request.POST)

        if allocated_form.is_valid():
            specific_expense.allocated = specific_expense.allocated + allocated_form.cleaned_data['allocate']
            specific_expense.remaining = specific_expense.allocated - specific_expense.disbursed
            specific_expense.save()
            return redirect('/')
    else:
        allocated_form = UpdateAllocationForm()
        related_transactions = Transaction.objects.filter(category=specific_expense.category)
        context = {
                'specific_expense':specific_expense,
                'allocated_form':allocated_form,
                'related_transactions':related_transactions
                }
        return render(request, 'budget_app/expense_detail.html', context)

def new_category_transaction(request):
    if request.method == 'POST':
        category_form = NewCategoryForm(request.POST)

        if category_form.is_valid():
            category_form.save()
            return redirect('budget_app:new_transaction')

    else:
        category_form = NewCategoryForm()
        return render(request, 'budget_app/category_new.html', {'category_form':category_form})

def new_category_expense(request):
    if request.method == 'POST':
        category_form = NewCategoryForm(request.POST)

        if category_form.is_valid():
            category_form.save()
            return redirect('budget_app:new_expense')

    else:
        category_form = NewCategoryForm()
        return render(request, 'budget_app/category_new.html', {'category_form':category_form})

def transaction_detail(request):
    monthly_transactions = Transaction.objects.all()
    return render(request, 'budget_app/transaction_detail.html', {'monthly_transactions':monthly_transactions})

def del_expense(request, expense_id):#needs DELETE method added
    to_delete = get_object_or_404(Expense, pk=expense_id)
    to_delete.delete()
    return redirect('/')

def add_next_month(request):
    if request.method == "POST":
        new_month()
        return redirect('/')
    else:
        return redirect('/')

budget_app/templates/budget_app/base.html
<!doctype html>

<html lang="en">

	<head>

        	<meta charset="utf-8">

        	<meta name="viewport" content="width=device-width, initial-scale=1">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
		<title>Expense Dashboard</title>

	</head>

	<header>

		<h1>Expenses</h1>
				
	</header>

	<body style="background-color:#E8E9C9;">
		{% block page_content %}
		{% endblock %}
	</body>

</html>

budget_app/templates/budget_app/category_new.html
{% extends 'budget_app/base.html' %}
  
        {% block page_content %}

	<h2>New Category</h2>
               <form method="POST">
		        {% csrf_token %}
                        {{ category_form }}
                	<button type="submit"class="btn btn-primary">Add</button>
                </form>

        {% endblock %}
~                                                        

budget_app/templates/budget_app/dashboard.html
{% extends 'budget_app/base.html' %}

	{% block page_content %}

		<button type="button" class="btn btn-link">
			<a href="{% url 'budget_app:new_expense' %}">
		      Add expense
			</a>
		</button>

		<a class="btn btn-primary" href="{% url 'budget_app:new_transaction' %}">
			New Transaction
		</a>

		<a class="btn btn-primary" href="{% url 'budget_app:transaction_detail' %}">
	        	View all Transactions
		</a>
		<form action="{% url 'budget_app:add_next_month' %}" method="POST">
			{% csrf_token %}
			<button type="submit" class="btn-btn-primary">New Month</button>
		</form>

	<br>
		<b>Unbudgeted</b>
	<br>
		${{ unbudgeted|floatformat:2 }}


		<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">Allocated</th>
		      <th scope="col">Category</th>
		      <th scope="col">Disbursed</th>
		      <th scope="col">Remaining</th>
		      <th scope="col"></th>
    		    </tr>
		  </thead>
		{% for expense in expenses %}
		  <tbody>
		    <tr>
			    <td>{{ expense.allocated }}</td>
			    <td><a href="{% url 'budget_app:expense_detail' expense.id %}">{{ expense.category }}</a></td>
			    <td>{{ expense.disbursed }}</td>
			    <td>{{ expense.remaining }}</td>
			    <td><a class="btn btn-default" href="{% url 'budget_app:del_expense' expense.id %}">Delete</a></td>
		    </tr>
		  </tbody>
	        {% endfor %}
		</table>	
{% endblock %}

budget_app/templates/budget_app/expense_add.html
{% extends 'budget_app/base.html' %}
	
	{% block page_content %}

		<h2>New Expense</h2>
		<form method="POST">{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="save btn btn-default">Save</button>
		</form>

	{% endblock %}

budget_app/templates/budget_app/expense_detail.html
{% extends 'budget_app/base.html' %}

	{% block page_content %}

		{{ specific_expense }}
			<h2>Allocate Money</h2>
			<br>
			Currently Allocated:{{ specific_expense.allocated }}
        		        <form method="POST">
					{% csrf_token %}
                        		{{ allocated_form }}
			                <button type="submit"class="btn btn-primary">Allocate</button>
		                </form>	

<table class="table">
	<thead>
        	<tr>
                	<th scope="col">Date</th>
                        <th scope="col">Recipient</th>
                        <th scope="col">Category</th>
                        <th scope="col">Inflow</th>
			<th scope="col">Outflow</th>
			<th scope="col">Note</th>
		</tr>
	</thead>
        {% for transaction in related_transactions %}
        	<tbody>
                	<tr>
                        	<td>{{ transaction.date }}</td>
				<td>{{ transaction.recipient }}</th>
                        	<td>{{ transaction.category }}</td>
                                <td>{{ transaction.inflow }}</td>
				<td>{{ transaction.outflow }}</td>
				<td>{{ transaction.note }}</td>
                        </tr>
		</tbody>
        {% endfor %}
</table>


{% endblock %}

budget_app/templates/budget_app/expense_list.html
{% extends 'budget_app/base.html' %}

{% block page_content %}

<a href="{% url 'budget_app:expense_new' %}">
      Add expense
</a>

	{% for expense in expenses %}
		<ul>
			<p>{{ expense.exp_type }}</p>
			<time>purchased: {{ expense.exp_date }}</time>
			<p>amount: {{ expense.amount }}</p>
			<form action="{% url 'budget_app:expense_del' pk=expense.pk %}" method="post">
				{% csrf_token %}
				<input type="submit" value="delete expense">
			</form>
		</ul>
		<br>
	{% endfor %}
{% endblock %}

budget_app/templates/budget_app/expense_new.html
{% extends 'budget_app/base.html' %}
	
	{% block page_content %}

		<h2>New Expense </h2>
		<form method="POST">{% csrf_token %}
			{{ expense_form }}
			<button type="submit"class="btn btn-primary">Add</button>
		</form>
		<br>
		<a class="btn btn-primary" href="{% url 'budget_app:new_category_expense' %}">
                	Add New Category
                </a>
	{% endblock %}

budget_app/templates/budget_app/new_pp.html
{% extends 'budget_app/base.html' %}
	
	{% block page_content %}

		<h2>New Pay Period</h2>
		<form method="POST">{% csrf_token %}
			{{ pp_form.as_ul }}
			<button type="submit" class="save btn btn-default">Save</button>
		</form>

	{% endblock %}

budget_app/templates/budget_app/transaction_detail.html
{% extends 'budget_app/base.html' %}

{% block page_content %}

<table class="table">
        <thead>
                <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Recipient</th>
                        <th scope="col">Category</th>
                        <th scope="col">Inflow</th>
                        <th scope="col">Outflow</th>
                        <th scope="col">Note</th>
                </tr>
        </thead>
        {% for transaction in monthly_transactions %}
                <tbody>
                        <tr>
                                <td>{{ transaction.date }}</td>
                                <td>{{ transaction.recipient }}</th>
                                <td>{{ transaction.category }}</td>
                                <td>{{ transaction.inflow }}</td>
                                <td>{{ transaction.outflow }}</td>
                                <td>{{ transaction.note }}</td>
                        </tr>
                </tbody>
        {% endfor %}
</table>


{% endblock %}

budget_app/templates/budget_app/transaction_new.html
{% extends 'budget_app/base.html' %}
	
	{% block page_content %}

		<h2>New Transaction </h2>
		<form method="POST">{% csrf_token %}
			{{ transaction_form.as_table }}
			<button type="submit"class="btn btn-primary">Add</button>
		</form>
		<a class="btn btn-primary" href="{% url 'budget_app:new_category_transaction' %}">
		       Add New Category
		</a>	
	{% endblock %}